### ISSUE TITLE
As a modeler, model and texture a cabinet

### ISSUE THREAD

**Issue by mr-mulligan** [UoSGamesGroups/level-6-l6-group-1#113]
The cabinet needs to follow our art style and early 19th century themed assets
- Aim to make a tall cabinet the size of a bookcase 
[2 hours]

**Comment by HatchyHatch14** [comment]
Cabinet model is done, and most of the texture. 

This model also has doors that still need to be textured, along with the Brass door handle nobs. The cabinet itself however is completely textured.
