### ISSUE TITLE
As a new group member, I want to research the material for the brief

### ISSUE THREAD

**Issue by mr-mulligan** [UoSGamesGroups/level-6-l6-group-1#55]
On our brief we have a variety of links that will help you gain an understanding of our project idea. 
Once you have looked through the links you must watch the following movies:
- Momento (2000 Christopher Nolan)
- Misery (1990 Stephen King)

[5 hours]

**Comment by HatchyHatch14** [comment]
Finished Watching Momento

**Comment by HatchyHatch14** [comment]
Finished Watching Misery, Rather enjoyable Film
