### ISSUE TITLE
As a new group member, I want to research our two rival games 

### ISSUE THREAD

**Issue by mr-mulligan** [UoSGamesGroups/level-6-l6-group-1#56]
The two rival games that we have are 'Torpor' and 'Gone Home'. You need to look into each game and understand their mechanics and compare them to our game.
[1 hour]

**Comment by HatchyHatch14** [comment]
Played Torpor on my PC with some difficulty but could easily see the models and low poly style the group is going for. 

Also tried Gone Home on PS4 and look at that game's models as well.
