### ISSUE TITLE
As a modeller, I want to create models of the coins

### ISSUE THREAD

**Issue by mr-mulligan** [UoSGamesGroups/level-6-l6-group-1#60]
There are three different kinds of coins:
- 50p Coin
- £1 Coin
- £2 Coin

We need a model for each of them and make them stand out from one another.
[1 hour]

**Comment by HatchyHatch14** [comment]
3 coins, a 50p a £1 and £2 coin are all modeled and textured with Silver, Gold and Silver and Gold texture colours to suit that type of coin.
