### ISSUE TITLE
As a modeler, I want to see some furniture in the game

### ISSUE THREAD

**Issue by mr-mulligan** [UoSGamesGroups/level-6-l6-group-1#61]
With the furniture we already have, go over the furniture to make sure they have no errors. The furniture should be low poly and textures should be block style similar to Torpor's art style.
Should do a minimum of 5 - 2 chairs, 1 table, 1 grandfather clock, 1 bookcase.
[3 hours]

**Comment by HatchyHatch14** [comment]
2 Chairs (one with arms and one without), 1 bookcase, 1 dresser are all done.

**Comment by HatchyHatch14** [comment]
Table and Grandfather Clock also done, might want to revisit The Clock before it goes into the game for a better shade of Wood Textures.
